name: tests
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 16

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - uses: coverallsapp/github-action@v1
        with:
          flag-name: node-${{ matrix.node }}-on-${{ matrix.os }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true
